title: Tarun's Blog
description: Yet another blog!
theme: just-the-docs

favicon_ico: /assets/favicon.png
color_scheme: dark
url: https://dugar-tarun.github.io/taruns-blog/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
